### ISSUE TITLE
grunt-bower-task is the wrong way

### ISSUE THREAD

**Issue by HaNdTriX** [smies/sails-generate-bower#1]
Hey @smies 

Thank you for this generator. 
I tried it and it works well, but the underlying [grunt-bower-task](https://github.com/yatskevich/grunt-bower-task) just doesn't work in the real world.

The reason for that is not the  [grunt-bower-task](https://github.com/yatskevich/grunt-bower-task), but the fact that people have different understandings of the bower.json file.
### Example: Bootstrap

Installing [bootstrap](http://getbootstrap.com/) with grunt-bower-task will create the following Directory:

Directory: `assets/vendor/bootstrap`

```
bootstrap.css                       // References a non existing source map
bootstrap.js                        // Do I must use all bootstrap js components?
bootstrap.less                      // Useless since references are missing
glyphicons-halflings-regular.eot    // Useless since not properly referenced by .css
glyphicons-halflings-regular.svg    // Useless since not properly referenced by .css
glyphicons-halflings-regular.ttf    // Useless since not properly referenced by .css
glyphicons-halflings-regular.woff   // Useless since not properly referenced by .css
```

This is just one example why the [grunt-bower-task](https://github.com/yatskevich/grunt-bower-task) is just not usable.
#### 1. Create a `.bowerrc` file.

```
{
    "directory": "assets/bower_components"
}
```

This tells bower to install all components in the assets folder.
#### 2. Add extra clean task

File: `tasks/config/clean.js`

```
module.exports = function(grunt) {

    grunt.config.set('clean', {
        dev: ['.tmp/public/**'],
        build: ['www'],
        bower: ['.tmp/public/bower_components/**']
    });

    grunt.loadNpmTasks('grunt-contrib-clean');
};
```
#### 3. Modify `grunt prod` task

We don't want to deploy entire git repos to production.

File: `tasks/config/clean.js`

```
module.exports = function (grunt) {
    grunt.registerTask('buildProd', [
        'compileAssets',
        'concat',
        'uglify',
        'cssmin',
        'linkAssetsBuildProd',
        'clean:bower',
        'clean:build',
        'copy:build'
    ]);
};
```
#### 4. Exclude `assets/bower_components` from the watch task

```
module.exports = function(grunt) {

    grunt.config.set('watch', {
        options: {
            livereload: true
        },
        api: {

            // API files to watch:
            files: ['api/**/*']
        },
        views: {

            // View files to watch:
            files: ['views/**/*']
        },
        assets: {

            // Assets to watch:
            files: ['assets/**/*' , '!assets/bower_components/**', 'tasks/pipeline.js'],

            // When assets are changed:
            tasks: ['syncAssets' , 'linkAssets']
        }
    });

    grunt.loadNpmTasks('grunt-contrib-watch');
};
```
#### Pros
- Now we can reference all files direct from the git repo. This allows us to pick only the files we need.
- Use bower directly without extra layer
#### Cons
- More complex to integrate.

What do you think of this approach?

**Comment by meltenc** [comment]
If anyone has the same issue, this is the right "exportsOverride" of the bower.json to install bootstrap correctly :

``` javascript
  "exportsOverride": {
    "bootstrap": {
      "js": "dist/js/*.min.*",
      "css": "dist/css/*.min.*",
      "fonts": "dist/fonts/*.*"
    }
  }
```
